version: 2.1

orbs:
  windows: circleci/windows@5

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "MyCarService.Tests/MyCarService.Tests.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "MyCarService.Tests/MyCarService.Tests.csproj" }}
      - run:
          name: "Install tool to collect test results"
          when: always
          command: dotnet.exe tool install -g trx2junit
      - run:
          name: "Build Application Tests"
          command: dotnet.exe build
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test --no-build --logger "trx"
      - run:
          name: "Conver .trx to .xml"
          command: trx2junit .\MyCarService.Tests\TestResults/*.trx
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_test_results:
          path: .\MyCarService.Tests\TestResults
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build
